#![warn(
    clippy::all,
    clippy::pedantic,
    clippy::correctness,
    clippy::perf,
    clippy::style,
    clippy::suspicious,
    clippy::complexity,
    clippy::nursery,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::as_conversions,
    clippy::dbg_macro,
    clippy::deprecated_cfg_attr,
    clippy::separated_literal_suffix,
    clippy::cargo,
    deprecated,
    trivial_casts,
    trivial_numeric_casts,
    unused_allocation,
    unused_qualifications,
    rust_2018_idioms
)]
#![forbid(unsafe_code, deprecated_in_future)]
